language: scala
sudo: false
matrix:
  include:
    - scala: 2.10.4
      script: ./sbt ++$TRAVIS_SCALA_VERSION clean test

    - scala: 2.11.5
      script:
        - ./sbt ++$TRAVIS_SCALA_VERSION clean coverage test &&
          ./sbt ++$TRAVIS_SCALA_VERSION coverageAggregate
      after_success: "./sbt ++$TRAVIS_SCALA_VERSION coveralls"
